## Building an Expected Goals (xG) Model

### 1. Data Collection
**StatsBomb open data** containing event and match information.
- One competition to test the logic: World Cup 2018
- Scale up to all competitions

---

### 2. Data Preparation
Get familiar with the data. 

---

### 3. Feature Engineering
Create meaningful variables that influence goal probability, such as **shot distance** and **angle**, as well as dummy variables where needed.

---

### 4. Model Development
Choose, train and compare a statistical or machine learning model to predict the probability of a goal from shot features.
- **logistic regression**
- **XGBoost**

---

### 5. Evaluation
Compare predictions to real outcomes or benchmark xG models. Assess model performance different metrics. Calculate xG of a competition/team/player to gain insights and visualize results, for example **shot maps**.

---

### 6. Deployment
Integrate the model into an application.

# 1. Data Collection

In [1]:
#pip install statsbombpy

In [2]:
#pip install mplsoccer

In [3]:
#pip install xgboost

In [4]:
#pip install pyarrow

In [7]:
#pip install joblib

In [9]:
#pip install streamlit

In [11]:
import warnings
from statsbombpy import sb
warnings.filterwarnings("ignore",message="credentials were not supplied. open data access only")

In [12]:
#Load competitions
competitions = sb.competitions()
competitions

,competition_id,season_id,country_name,competition_name,competition_gender,competition_youth,competition_international,season_name,match_updated,match_updated_360,match_available_360,match_available
0,9,281,Germany,1. Bundesliga,male,False,False,2023/2024,2024-09-28T20:46:38.893391,2025-07-06T04:26:07.636270,2025-07-06T04:26:07.636270,2024-09-28T20:46:38.893391
1,9,27,Germany,1. Bundesliga,male,False,False,2015/2016,2024-05-19T11:11:14.192381,None,None,2024-05-19T11:11:14.192381
2,1267,107,Africa,African Cup of Nations,male,False,True,2023,2024-09-28T01:57:35.846538,None,None,2024-09-28T01:57:35.846538
3,16,4,Europe,Champions League,male,False,False,2018/2019,2025-05-08T15:10:50.835274,2021-06-13T16:17:31.694,None,2025-05-08T15:10:50.835274
4,16,1,Europe,Champions League,male,False,False,2017/2018,2024-02-13T02:35:28.134882,2021-06-13T16:17:31.694,None,2024-02-13T02:35:28.134882
...,...,...,...,...,...,...,...,...,...,...,...,...
70,35,75,Europe,UEFA Europa League,male,False,False,1988/1989,2024-02-12T14:45:05.702250,2021-06-13T16:17:31.694,None,2024-02-12T14:45:05.702250
71,53,315,Europe,UEFA Women's Euro,female,False,True,2025,2025-07-28T14:19:20.467348,2025-07-29T16:03:07.355174,2025-07-29T16:03:07.355174,2025-07-28T14:19:20.467348
72,53,106,Europe,UEFA Women's Euro,female,False,True,2022,2024-02-13T13:27:17.178263,2024-02-13T13:30:52.820588,2024-02-13T13:30:52.820588,2024-02-13T13:27:17.178263
73,72,107,International,Women's World Cup,female,False,True,2023,2025-07-14T10:07:06.620906,2025-07-14T10:10:27.224586,2025-07-14T10:10:27.224586,2025-07-14T10:07:06.620906
74,72,30,International,Women's World Cup,female,False,True,2019,2024-08-08T15:57:56.748740,2021-06-13T16:17:31.694,None,2024-08-08T15:57:56.748740

In [13]:
#Load matches from competition: 2018 World Cup
matches = sb.matches(competition_id=43, season_id=3)
matches

,match_id,match_date,kick_off,competition,season,home_team,away_team,home_score,away_score,match_status,...,last_updated_360,match_week,competition_stage,stadium,referee,home_managers,away_managers,data_version,shot_fidelity_version,xy_fidelity_version
0,7585,2018-07-03,20:00:00.000,International - FIFA World Cup,2018,Colombia,England,1,1,available,...,2021-06-13T16:17:31.694,4,Round of 16,Otkritie Bank Arena,Mark Geiger,José Néstor Pekerman,Gareth Southgate,1.0.2,None,None
1,7570,2018-06-28,20:00:00.000,International - FIFA World Cup,2018,England,Belgium,0,1,available,...,2021-06-13T16:17:31.694,3,Group Stage,Stadion Kaliningrad,Damir Skomina,Gareth Southgate,Roberto Martínez Montoliú,1.0.2,None,None
2,7586,2018-07-03,16:00:00.000,International - FIFA World Cup,2018,Sweden,Switzerland,1,0,available,...,2021-06-13T16:17:31.694,4,Round of 16,Saint-Petersburg Stadium,Damir Skomina,Jan Olof Andersson,Vladimir Petković,1.0.2,None,None
3,7557,2018-06-25,20:00:00.000,International - FIFA World Cup,2018,Iran,Portugal,1,1,available,...,2021-06-13T16:17:31.694,3,Group Stage,Mordovia Arena,Enrique Cáceres,Carlos Manuel Brito Leal Queiróz,Fernando Manuel Fernandes da Costa Santos,1.0.2,None,None
4,7542,2018-06-20,14:00:00.000,International - FIFA World Cup,2018,Portugal,Morocco,1,0,available,...,2021-06-13T16:17:31.694,2,Group Stage,Stadion Luzhniki,Mark Geiger,Fernando Manuel Fernandes da Costa Santos,Hervé Renard,1.0.2,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
59,7540,2018-06-19,20:00:00.000,International - FIFA World Cup,2018,Russia,Egypt,3,1,available,...,2021-06-13T16:17:31.694,2,Group Stage,Saint-Petersburg Stadium,Enrique Cáceres,Stanislav Cherchesov,Héctor Raúl Cúper,1.0.2,None,None
60,8652,2018-07-07,20:00:00.000,International - FIFA World Cup,2018,Russia,Croatia,2,2,available,...,2021-06-13T16:17:31.694,5,Quarter-finals,\tOlimpiyskiy Stadion Fisht,Sandro Ricci,Stanislav Cherchesov,Zlatko Dalić,1.0.2,None,None
61,7563,2018-06-26,16:00:00.000,International - FIFA World Cup,2018,Denmark,France,0,0,available,...,2021-06-13T16:17:31.694,3,Group Stage,Stadion Luzhniki,Sandro Ricci,Åge Fridtjof Hareide,Didier Deschamps,1.0.2,None,None
62,7556,2018-06-24,17:00:00.000,International - FIFA World Cup,2018,Japan,Senegal,2,2,available,...,2021-06-13T16:17:31.694,2,Group Stage,\tEkaterinburg Arena,Gianluca Rocchi,Akira Nishino,Aliou Cissé,1.0.2,None,None
63,7559,2018-06-25,16:00:00.000,International - FIFA World Cup,2018,Saudi Arabia,Egypt,2,1,available,...,2021-06-13T16:17:31.694,3,Group Stage,Volgograd Arena,Wilmar Alexander Roldán Pérez,Juan Antonio Pizzi Torroja,Héctor Raúl Cúper,1.0.2,None,None

In [14]:
events = sb.events(matches["match_id"].iloc[0])
events

,50_50,bad_behaviour_card,ball_receipt_outcome,ball_recovery_recovery_failure,block_deflection,block_offensive,carry_end_location,clearance_aerial_won,counterpress,dribble_nutmeg,...,substitution_outcome,substitution_outcome_id,substitution_replacement,substitution_replacement_id,tactics,team,team_id,timestamp,type,under_pressure
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,"{'formation': 433, 'lineup': [{'player': {'id'...",Colombia,769,00:00:00.000,Starting XI,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,"{'formation': 352, 'lineup': [{'player': {'id'...",England,768,00:00:00.000,Starting XI,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,England,768,00:00:00.000,Half Start,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,Colombia,769,00:00:00.000,Half Start,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,Colombia,769,00:00:00.000,Half Start,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4014,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Tactical,103.0,Marcus Rashford,3318.0,NaN,England,768,00:07:33.493,Substitution,NaN
4015,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Tactical,103.0,Cristian Eduardo Zapata Valencia,6360.0,NaN,Colombia,769,00:10:17.880,Substitution,NaN
4016,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,"{'formation': 442, 'lineup': [{'player': {'id'...",Colombia,769,00:16:06.374,Tactical Shift,NaN
4017,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,Colombia,769,00:31:38.320,Camera off,NaN
4018,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,England,768,00:41:49.320,Camera off,NaN

In [15]:
import pandas as pd

all_events = []

# Loop through each match
for match_id in matches["match_id"]:
    events = sb.events(match_id=match_id)
    events["match_id"] = match_id
    all_events.append(events)
# Concatenate all event DataFrames into one
events_df = pd.concat(all_events, ignore_index=True)
print("✅ All match events collected and saved!")
events_df

✅ All match events collected and saved!

,50_50,bad_behaviour_card,ball_receipt_outcome,ball_recovery_recovery_failure,block_deflection,block_offensive,carry_end_location,clearance_aerial_won,counterpress,dribble_nutmeg,...,foul_committed_offensive,injury_stoppage_in_chain,pass_cut_back,pass_technique,pass_through_ball,shot_one_on_one,ball_recovery_offensive,miscontrol_aerial_won,pass_miscommunication,shot_redirect
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
227844,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
227845,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
227846,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
227847,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
227848,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

# 2. Data Preparation

In [16]:
events_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 227849 entries, 0 to 227848
Data columns (total 95 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   50_50                           108 non-null     object
 1   bad_behaviour_card              40 non-null      object
 2   ball_receipt_outcome            8800 non-null    object
 3   ball_recovery_recovery_failure  512 non-null     object
 4   block_deflection                79 non-null      object
 5   block_offensive                 43 non-null      object
 6   carry_end_location              50521 non-null   object
 7   clearance_aerial_won            151 non-null     object
 8   counterpress                    6470 non-null    object
 9   dribble_nutmeg                  99 non-null      object
 10  dribble_outcome                 2109 non-null    object
 11  duel_outcome                    1830 non-null    object
 12  duel_type                       3141 non-null    object
 13  duration                        143014 non-null  float64
 14  foul_committed_advantage        168 non-null     object
 15  foul_committed_card             169 non-null     object
 16  foul_committed_penalty          27 non-null      object
 17  foul_committed_type             101 non-null     object
 18  foul_won_advantage              174 non-null     object
 19  foul_won_defensive              527 non-null     object
 20  foul_won_penalty                19 non-null      object
 21  goalkeeper_body_part            359 non-null     object
 22  goalkeeper_end_location         1176 non-null    object
 23  goalkeeper_outcome              790 non-null     object
 24  goalkeeper_position             1706 non-null    object
 25  goalkeeper_technique            511 non-null     object
 26  goalkeeper_type                 1975 non-null    object
 27  id                              227849 non-null  object
 28  index                           227849 non-null  int64
 29  interception_outcome            1276 non-null    object
 30  location                        224041 non-null  object
 31  match_id                        227849 non-null  int64
 32  minute                          227849 non-null  int64
 33  pass_aerial_won                 1022 non-null    object
 34  pass_angle                      62881 non-null   float64
 35  pass_assisted_shot_id           1180 non-null    object
 36  pass_backheel                   364 non-null     object
 37  pass_body_part                  59654 non-null   object
 38  pass_cross                      1685 non-null    object
 39  pass_deflected                  85 non-null      object
 40  pass_end_location               62881 non-null   object
 41  pass_goal_assist                96 non-null      object
 42  pass_height                     62881 non-null   object
 43  pass_length                     62881 non-null   float64
 44  pass_outcome                    12714 non-null   object
 45  pass_recipient                  58972 non-null   object
 46  pass_recipient_id               58972 non-null   float64
 47  pass_shot_assist                1084 non-null    object
 48  pass_switch                     2033 non-null    object
 49  pass_type                       11260 non-null   object
 50  period                          227849 non-null  int64
 51  play_pattern                    227849 non-null  object
 52  player                          224539 non-null  object
 53  player_id                       224539 non-null  float64
 54  position                        224539 non-null  object
 55  possession                      227849 non-null  int64
 56  possession_team                 227849 non-null  object
 57  possession_team_id              227849 non-null  int64
 58  related_events                  216660 non-null  object
 59  second                          227849 non-null  int64
 60  shot_aerial_won                 124 non-null     object
 61  shot_body_part                  1706 non-null    object
 62  shot_deflected                  17 non-null      object
 63  shot_end_location               1706 non-null    object
 64  shot_first_time                 357 non-null     object
 65  shot_follows_dribble            2 non-null       object
 66  shot_freeze_frame               1638 non-null    object
 67  shot_key_pass_id                1180 non-null    object
 68  shot_open_goal                  17 non-null      object
 69  shot_outcome                    1706 non-null    object
 70  shot_statsbomb_xg               1706 non-null    float64
 71  shot_technique                  1706 non-null    object
 72  shot_type                       1706 non-null    object
 73  substitution_outcome            378 non-null     object
 74  substitution_outcome_id         378 non-null     float64
 75  substitution_replacement        382 non-null     object
 76  substitution_replacement_id     382 non-null     float64
 77  tactics                         244 non-null     object
 78  team                            227849 non-null  object
 79  team_id                         227849 non-null  int64
 80  timestamp                       227849 non-null  object
 81  type                            227849 non-null  object
 82  under_pressure                  51894 non-null   object
 83  block_save_block                10 non-null      object
 84  dribble_overrun                 173 non-null     object
 85  foul_committed_offensive        86 non-null      object
 86  injury_stoppage_in_chain        37 non-null      object
 87  pass_cut_back                   86 non-null      object
 88  pass_technique                  71 non-null      object
 89  pass_through_ball               71 non-null      object
 90  shot_one_on_one                 55 non-null      object
 91  ball_recovery_offensive         46 non-null      object
 92  miscontrol_aerial_won           14 non-null      object
 93  pass_miscommunication           25 non-null      object
 94  shot_redirect                   6 non-null       object
dtypes: float64(8), int64(8), object(79)
memory usage: 165.1+ MB

In [17]:
for column in events_df:
    if column in ["tactics","pass_recipient","pass_recipient_id","player","player_id",
                  "substitution_replacement","substitution_replacement_id"]:
        continue
    if events_df[column].apply(lambda x: isinstance(x, (dict,list))).any():
        events_df[column] = events_df[column].apply(str)

    print(f"\nColumn: {column}")
    print(events_df[column].unique())

Column: 50_50
['nan' "{'outcome': {'id': 1, 'name': 'Lost'}}"
 "{'outcome': {'id': 3, 'name': 'Success To Team'}}"
 "{'outcome': {'id': 2, 'name': 'Success To Opposition'}}"
 "{'outcome': {'id': 4, 'name': 'Won'}}"]

Column: bad_behaviour_card
[nan 'Yellow Card']

Column: ball_receipt_outcome
[nan 'Incomplete']

Column: ball_recovery_recovery_failure
[nan True]

Column: block_deflection
[nan True]

Column: block_offensive
[nan True]

Column: carry_end_location
['nan' '[51.0, 40.0]' '[49.0, 55.0]' ... '[90.0, 46.0]' '[15.0, 23.0]'
 '[103.0, 38.0]']

Column: clearance_aerial_won
[nan True]

Column: counterpress
[nan True]

Column: dribble_nutmeg
[nan True]

Column: dribble_outcome
[nan 'Incomplete' 'Complete']

Column: duel_outcome
[nan 'Lost In Play' 'Success In Play' 'Won' 'Lost Out' 'Success Out']

Column: duel_type
[nan 'Tackle' 'Aerial Lost']

Column: duration
[0.    0.754 9.32  ... 4.268 3.407 6.679]

Column: foul_committed_advantage
[nan True]

Column: foul_committed_card
[nan 'Yellow Card' 'Red Card' 'Second Yellow']

Column: foul_committed_penalty
[nan True]

Column: foul_committed_type
[nan 'Handball' 'Dangerous Play' 'Dive' 'Foul Out']

Column: foul_won_advantage
[nan True]

Column: foul_won_defensive
[nan True]

Column: foul_won_penalty
[nan True]

Column: goalkeeper_body_part
[nan 'Both Hands' 'Left Hand' 'Right Hand' 'Left Foot' 'Right Foot'
 'Chest' 'Head']

Column: goalkeeper_end_location
['nan' '[3.0, 37.0]' '[2.0, 41.0]' '[2.0, 42.0]' '[2.0, 38.0]'
 '[1.0, 40.0]' '[2.0, 43.0]' '[1.0, 41.0]' '[2.0, 40.0]' '[3.0, 43.0]'
 '[1.0, 39.0]' '[2.0, 36.0]' '[2.0, 39.0]' '[3.0, 42.0]' '[3.0, 39.0]'
 '[3.0, 40.0]' '[4.0, 49.0]' '[2.0, 44.0]' '[4.0, 39.0]' '[5.0, 41.0]'
 '[3.0, 41.0]' '[9.0, 38.0]' '[1.0, 38.0]' '[4.0, 42.0]' '[5.0, 45.0]'
 '[2.0, 37.0]' '[1.0, 42.0]' '[3.0, 38.0]' '[7.0, 39.0]' '[4.0, 40.0]'
 '[4.0, 38.0]' '[4.0, 41.0]' '[3.0, 44.0]' '[6.0, 40.0]' '[37.0, 24.0]'
 '[5.0, 43.0]' '[7.0, 38.0]' '[11.0, 41.0]' '[4.0, 44.0]' '[3.0, 36.0]'
 '[3.0, 45.0]' '[5.0, 35.0]' '[4.0, 46.0]' '[5.0, 42.0]' '[4.0, 37.0]'
 '[5.0, 37.0]' '[6.0, 46.0]' '[5.0, 40.0]' '[2.0, 46.0]' '[1.0, 37.0]'
 '[3.0, 48.0]' '[6.0, 37.0]' '[4.0, 43.0]' '[1.0, 43.0]' '[8.0, 28.0]'
 '[9.0, 40.0]' '[6.0, 41.0]' '[5.0, 44.0]' '[2.0, 45.0]' '[8.0, 45.0]'
 '[5.0, 39.0]' '[5.0, 36.0]' '[2.0, 35.0]' '[5.0, 38.0]' '[6.0, 43.0]'
 '[5.0, 48.0]' '[4.0, 50.0]' '[1.0, 44.0]' '[4.0, 45.0]' '[9.0, 45.0]'
 '[7.0, 43.0]' '[6.0, 35.0]' '[13.0, 49.0]' '[2.0, 33.0]' '[4.0, 47.0]'
 '[6.0, 47.0]' '[9.0, 42.0]' '[16.0, 28.0]' '[7.0, 32.0]' '[13.0, 42.0]']

Column: goalkeeper_outcome
[nan 'In Play Safe' 'Success' 'No Touch' 'Touched Out' 'Clear'
 'Touched In' 'In Play Danger' 'Saved Twice' 'Fail' 'Claim'
 'Collected Twice' 'Won' 'Lost']

Column: goalkeeper_position
[nan 'Set' 'Moving' 'Prone']

Column: goalkeeper_technique
[nan 'Standing' 'Diving']

Column: goalkeeper_type
[nan 'Shot Saved' 'Collected' 'Shot Faced' 'Penalty Conceded'
 'Goal Conceded' 'Keeper Sweeper' 'Punch' 'Penalty Saved' 'Smother' 'Save']

Column: id
['de3be98d-e227-475b-bd55-f57a6a89d308'
 'f50ccda4-b768-4f07-9136-8f79fd17dac5'
 'b5e98805-0a22-4a5e-a306-7d40651a0f6e' ...
 'a0143404-6921-4588-a4a6-2dc882c59447'
 '02496cdc-24e5-48e6-a9bc-10e598064edc'
 'ea485df9-9d5c-455f-b8ba-48523de17a89']

Column: index
[   1    2    3 ... 4427 4768 4960]

Column: interception_outcome
[nan 'Success In Play' 'Lost Out' 'Won' 'Lost In Play' 'Success Out']

Column: location
['nan' '[60.0, 40.0]' '[51.0, 40.0]' ... '[116.0, 54.0]' '[115.0, 10.0]'
 '[112.0, 25.0]']

Column: match_id
[7585 7570 7586 7557 7542 8656 7554 7550 7548 7578 7553 7544 7536 7555
 7546 7539 7538 7576 7565 7551 7537 7580 8650 7581 7549 7529 7534 7562
 7571 7569 7568 7530 7558 7583 7547 7535 7584 7545 8649 8658 7561 7531
 7582 7552 7532 7560 7533 7564 7579 7572 7577 7543 7525 7566 8651 7567
 7541 8655 8657 7540 8652 7563 7556 7559]

Column: minute
[  0  45  90 105 120   1   2   3   4   5   6   7   8   9  10  11  12  13
  14  15  16  17  18  19  20  21  22  23  24  25  26  27  28  29  30  31
  32  33  34  35  36  37  41  42  43  44  46  48  49  47  50  51  52  53
  57  58  59  60  61  62  63  64  65  66  68  69  70  71  72  73  74  75
  76  77  78  79  80  81  82  83  84  85  86  87  88  89  91  92  94  95
  96  93  97  98  99 100 101 102 103 104 106 107 108 109 110 111 113 114
 115 116 117 118 119 121  56 122 123 124 125 126 127  40  55 112  38  39
  54  67 128]

Column: pass_aerial_won
[nan True]

Column: pass_angle
[       nan  3.041924   1.849096  ...  0.6066051 -0.6871242  1.6287025]

Column: pass_assisted_shot_id
[nan '3d830e92-8719-4b07-aa8b-cf5772a80873'
 'b7213f46-90f2-4b3c-acdd-bf4f89846df9' ...
 '5ce39d13-e290-428b-844e-c0a611a0035a'
 '5394cab7-ad64-45da-9e7c-df7669414773'
 '84855116-f3ee-4671-b757-b9ce80d79008']

Column: pass_backheel
[nan True]

Column: pass_body_part
[nan 'Left Foot' 'Right Foot' 'Head' 'Keeper Arm' 'Other' 'Drop Kick']

Column: pass_cross
[nan True]

Column: pass_deflected
[nan True]

Column: pass_end_location
['nan' '[50.0, 41.0]' '[47.0, 54.0]' ... '[25.0, 45.0]' '[20.0, 8.0]'
 '[116.0, 59.0]']

Column: pass_goal_assist
[nan True]

Column: pass_height
[nan 'Ground Pass' 'High Pass' 'Low Pass']

Column: pass_length
[      nan 10.049875 14.56022  ... 65.946945 60.835846 72.718636]

Column: pass_outcome
[nan 'Incomplete' 'Unknown' 'Out' 'Pass Offside' 'Injury Clearance']

Column: pass_shot_assist
[nan True]

Column: pass_switch
[nan True]

Column: pass_type
[nan 'Kick Off' 'Recovery' 'Free Kick' 'Corner' 'Throw-in' 'Goal Kick'
 'Interception']

Column: period
[1 2 3 4 5]

Column: play_pattern
['Regular Play' 'From Free Kick' 'From Kick Off' 'From Corner'
 'From Keeper' 'From Throw In' 'From Counter' 'From Goal Kick' 'Other']

Column: position
[nan 'Left Center Forward' 'Center Attacking Midfield'
 'Right Center Midfield' 'Right Back' 'Left Center Back'
 'Left Attacking Midfield' 'Right Center Forward'
 'Right Attacking Midfield' 'Right Center Back' 'Left Center Midfield'
 'Goalkeeper' 'Center Back' 'Center Defensive Midfield' 'Left Midfield'
 'Right Midfield' 'Left Back' 'Left Wing' 'Right Wing' 'Center Forward'
 'Left Defensive Midfield' 'Right Defensive Midfield' 'Center Midfield'
 'Right Wing Back' 'Left Wing Back' 'Secondary Striker']

Column: possession
[  1  79 155 180 212   2   3   4   5   6   7   8   9  10  11  12  13  14
  15  17  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33
  34  35  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51
  52  53  54  55  56  57  58  59  60  61  62  63  64  65  67  68  69  70
  71  72  73  74  75  77  78  80  81  82  83  84  85  86  87  88  89  90
  91  92  94  95  96  97  98  99 100 101 102 103 104 105 106 107 108 109
 110 111 112 113 114 115 116 117 118 119 120 121 122 123 125 126 127 128
 129 130 131 132 133 134 136 137 138 139 140 142 143 144 145 146 148 149
 151 153 154 156 157 158 159 160 161 162 163 164 165 166 167 168 169 170
 171 172 174 175 176 177 178 179 181 182 183 184 185 186 187 188 189 190
 191 192 193 194 195 196 197 198 199 200 201 202 203 204 205 206 207 208
 209 211  16 135 147 173 210 124 152  66  93 213 214 215 216 217 218 220
 221 222 224  76 141 150 219 223 226 227 229 230 231 232 233 234 235 236
 237 238 239 240 241 242 228 225 243]

Column: possession_team
['Colombia' 'England' 'Belgium' 'Sweden' 'Switzerland' 'Iran' 'Portugal'
 'Morocco' 'Croatia' 'Panama' 'Serbia' 'Brazil' 'Costa Rica' 'Egypt'
 'Uruguay' 'South Korea' 'Mexico' 'Saudi Arabia' 'Poland' 'France' 'Peru'
 'Senegal' 'Spain' 'Germany' 'Tunisia' 'Argentina' 'Denmark' 'Nigeria'
 'Iceland' 'Australia' 'Russia' 'Japan']

Column: possession_team_id
[769 768 782 790 773 797 780 788 785 798 786 781 795 774 783 791 794 799
 789 771 784 787 772 770 777 779 776 775 793 792 796 778]

Column: related_events
['nan' "['762b829f-5f24-4dd7-bfe2-da7e289838bb']"
 "['b5e98805-0a22-4a5e-a306-7d40651a0f6e']" ...
 "['53881f94-811f-49c5-9675-ca00bba94ee6']"
 "['ea485df9-9d5c-455f-b8ba-48523de17a89']"
 "['02496cdc-24e5-48e6-a9bc-10e598064edc']"]

Column: second
[ 0  2  4  6  8 11 12 14 16 17 27 33 35 38 41 44 47 50 57  1  9 19 21 25
 30 39 46 51 53 55 58  7 15 20 22 24 26 28 36 43 48 49 59  5 23 40  3 13
 18 31 34 56 42 45 54 29 32 10 52 37]

Column: shot_aerial_won
[nan True]

Column: shot_body_part
[nan 'Right Foot' 'Head' 'Left Foot' 'Other']

Column: shot_deflected
[nan True]

Column: shot_end_location
['nan' '[120.0, 42.2, 2.0]' '[113.0, 53.0]' ... '[120.0, 44.2, 4.2]'
 '[104.0, 32.0]' '[119.0, 36.8, 0.8]']

Column: shot_first_time
[nan True]

Column: shot_follows_dribble
[nan True]

Column: shot_freeze_frame
['nan'
 "[{'location': [116.0, 41.0], 'player': {'id': 10955, 'name': 'Harry Kane'}, 'position': {'id': 24, 'name': 'Left Center Forward'}, 'teammate': True}, {'location': [95.0, 42.0], 'player': {'id': 3308, 'name': 'Kieran Trippier'}, 'position': {'id': 12, 'name': 'Right Midfield'}, 'teammate': True}, {'location': [109.0, 39.0], 'player': {'id': 3532, 'name': 'Jordan Brian Henderson'}, 'position': {'id': 10, 'name': 'Center Defensive Midfield'}, 'teammate': True}, {'location': [109.0, 49.0], 'player': {'id': 3336, 'name': 'Harry Maguire'}, 'position': {'id': 5, 'name': 'Left Center Back'}, 'teammate': True}, {'location': [110.0, 47.0], 'player': {'id': 3244, 'name': 'John Stones'}, 'position': {'id': 4, 'name': 'Center Back'}, 'teammate': True}, {'location': [111.0, 44.0], 'player': {'id': 3233, 'name': 'Raheem Sterling'}, 'position': {'id': 22, 'name': 'Right Center Forward'}, 'teammate': True}, {'location': [118.0, 43.0], 'player': {'id': 3094, 'name': 'Bamidele Alli'}, 'position': {'id': 20, 'name': 'Left Attacking Midfield'}, 'teammate': True}, {'location': [107.0, 20.0], 'player': {'id': 3293, 'name': 'Jesse Lingard'}, 'position': {'id': 18, 'name': 'Right Attacking Midfield'}, 'teammate': True}, {'location': [111.0, 48.0], 'player': {'id': 5678, 'name': 'Jefferson Andrés Lerma Solís'}, 'position': {'id': 15, 'name': 'Left Center Midfield'}, 'teammate': False}, {'location': [114.0, 49.0], 'player': {'id': 3494, 'name': 'Davinson Sánchez Mina'}, 'position': {'id': 5, 'name': 'Left Center Back'}, 'teammate': False}, {'location': [117.0, 42.0], 'player': {'id': 5685, 'name': 'Carlos Alberto Sánchez Moreno'}, 'position': {'id': 13, 'name': 'Right Center Midfield'}, 'teammate': False}, {'location': [117.0, 28.0], 'player': {'id': 5692, 'name': 'Juan Fernando Quintero Paniagua'}, 'position': {'id': 19, 'name': 'Center Attacking Midfield'}, 'teammate': False}, {'location': [118.0, 45.0], 'player': {'id': 5686, 'name': 'Wílmar Enrique Barrios Terán'}, 'position': {'id': 10, 'name': 'Center Defensive Midfield'}, 'teammate': False}, {'location': [117.0, 37.0], 'player': {'id': 3445, 'name': 'Radamel Falcao García Zárate'}, 'position': {'id': 24, 'name': 'Left Center Forward'}, 'teammate': False}, {'location': [111.0, 43.0], 'player': {'id': 5696, 'name': 'Santiago Arias Naranjo'}, 'position': {'id': 2, 'name': 'Right Back'}, 'teammate': False}, {'location': [110.0, 40.0], 'player': {'id': 5691, 'name': 'Johan Andrés Mojica Palacio'}, 'position': {'id': 6, 'name': 'Left Back'}, 'teammate': False}, {'location': [114.0, 40.0], 'player': {'id': 6196, 'name': 'Yerry Fernando Mina González'}, 'position': {'id': 3, 'name': 'Right Center Back'}, 'teammate': False}, {'location': [120.0, 41.0], 'player': {'id': 4276, 'name': 'David Ospina Ramírez'}, 'position': {'id': 1, 'name': 'Goalkeeper'}, 'teammate': False}, {'location': [116.0, 28.0], 'player': {'id': 5689, 'name': 'Juan Guillermo Cuadrado Bello'}, 'position': {'id': 22, 'name': 'Right Center Forward'}, 'teammate': False}]"
 "[{'location': [102.0, 40.0], 'player': {'id': 10955, 'name': 'Harry Kane'}, 'position': {'id': 24, 'name': 'Left Center Forward'}, 'teammate': True}, {'location': [105.0, 54.0], 'player': {'id': 3445, 'name': 'Radamel Falcao García Zárate'}, 'position': {'id': 24, 'name': 'Left Center Forward'}, 'teammate': False}, {'location': [114.0, 53.0], 'player': {'id': 6196, 'name': 'Yerry Fernando Mina González'}, 'position': {'id': 3, 'name': 'Right Center Back'}, 'teammate': False}, {'location': [91.0, 43.0], 'player': {'id': 3244, 'name': 'John Stones'}, 'position': {'id': 4, 'name': 'Center Back'}, 'teammate': True}, {'location': [92.0, 47.0], 'player': {'id': 3532, 'name': 'Jordan Brian Henderson'}, 'position': {'id': 10, 'name': 'Center Defensive Midfield'}, 'teammate': True}, {'location': [98.0, 46.0], 'player': {'id': 3293, 'name': 'Jesse Lingard'}, 'position': {'id': 18, 'name': 'Right Attacking Midfield'}, 'teammate': True}, {'location': [90.0, 39.0], 'player': {'id': 5689, 'name': 'Juan Guillermo Cuadrado Bello'}, 'position': {'id': 22, 'name': 'Right Center Forward'}, 'teammate': False}, {'location': [103.0, 40.0], 'player': {'id': 5685, 'name': 'Carlos Alberto Sánchez Moreno'}, 'position': {'id': 13, 'name': 'Right Center Midfield'}, 'teammate': False}, {'location': [99.0, 39.0], 'player': {'id': 5696, 'name': 'Santiago Arias Naranjo'}, 'position': {'id': 2, 'name': 'Right Back'}, 'teammate': False}, {'location': [105.0, 44.0], 'player': {'id': 5678, 'name': 'Jefferson Andrés Lerma Solís'}, 'position': {'id': 15, 'name': 'Left Center Midfield'}, 'teammate': False}, {'location': [112.0, 53.0], 'player': {'id': 5691, 'name': 'Johan Andrés Mojica Palacio'}, 'position': {'id': 6, 'name': 'Left Back'}, 'teammate': False}, {'location': [105.0, 41.0], 'player': {'id': 3094, 'name': 'Bamidele Alli'}, 'position': {'id': 20, 'name': 'Left Attacking Midfield'}, 'teammate': True}, {'location': [106.0, 35.0], 'player': {'id': 3336, 'name': 'Harry Maguire'}, 'position': {'id': 5, 'name': 'Left Center Back'}, 'teammate': True}, {'location': [109.0, 43.0], 'player': {'id': 5686, 'name': 'Wílmar Enrique Barrios Terán'}, 'position': {'id': 10, 'name': 'Center Defensive Midfield'}, 'teammate': False}, {'location': [109.0, 35.0], 'player': {'id': 3494, 'name': 'Davinson Sánchez Mina'}, 'position': {'id': 5, 'name': 'Left Center Back'}, 'teammate': False}, {'location': [120.0, 44.0], 'player': {'id': 4276, 'name': 'David Ospina Ramírez'}, 'position': {'id': 1, 'name': 'Goalkeeper'}, 'teammate': False}]"
 ...
 "[{'location': [104.0, 41.0], 'player': {'id': 3568, 'name': 'Mohamed Naser Elsayed Elneny'}, 'position': {'id': 13, 'name': 'Right Center Midfield'}, 'teammate': False}, {'location': [112.0, 36.0], 'player': {'id': 5716, 'name': 'Hussain Al Mogahwi'}, 'position': {'id': 15, 'name': 'Left Center Midfield'}, 'teammate': True}, {'location': [113.0, 42.0], 'player': {'id': 5176, 'name': 'Mohanad Aseri Abu Radiah'}, 'position': {'id': 23, 'name': 'Center Forward'}, 'teammate': True}, {'location': [112.0, 47.0], 'player': {'id': 4063, 'name': 'Ahmed Elsayed Ali Elsayed Hegazy'}, 'position': {'id': 5, 'name': 'Left Center Back'}, 'teammate': False}, {'location': [112.0, 40.0], 'player': {'id': 5254, 'name': 'Ali Gabr'}, 'position': {'id': 3, 'name': 'Right Center Back'}, 'teammate': False}, {'location': [118.0, 39.0], 'player': {'id': 6292, 'name': 'Essam Kamal Tawfik El Hadary'}, 'position': {'id': 1, 'name': 'Goalkeeper'}, 'teammate': False}, {'location': [115.0, 33.0], 'player': {'id': 5250, 'name': 'Ahmed Fathy Abdel Meneim Ibrahim'}, 'position': {'id': 2, 'name': 'Right Back'}, 'teammate': False}, {'location': [114.0, 31.0], 'player': {'id': 5253, 'name': 'Amr Medhat Warda'}, 'position': {'id': 17, 'name': 'Right Wing'}, 'teammate': False}]"
 "[{'location': [87.0, 66.0], 'player': {'id': 3536, 'name': 'Ramadan Sobhi Ramadan Ahmed'}, 'position': {'id': 21, 'name': 'Left Wing'}, 'teammate': False}, {'location': [102.0, 50.0], 'player': {'id': 3568, 'name': 'Mohamed Naser Elsayed Elneny'}, 'position': {'id': 13, 'name': 'Right Center Midfield'}, 'teammate': False}, {'location': [101.0, 57.0], 'player': {'id': 5262, 'name': 'Tarek Hamed'}, 'position': {'id': 15, 'name': 'Left Center Midfield'}, 'teammate': False}, {'location': [106.0, 58.0], 'player': {'id': 5263, 'name': 'Mohamed Abdul Shafy Sayed Abouezeid'}, 'position': {'id': 6, 'name': 'Left Back'}, 'teammate': False}, {'location': [105.0, 53.0], 'player': {'id': 4063, 'name': 'Ahmed Elsayed Ali Elsayed Hegazy'}, 'position': {'id': 5, 'name': 'Left Center Back'}, 'teammate': False}, {'location': [120.0, 44.0], 'player': {'id': 6292, 'name': 'Essam Kamal Tawfik El Hadary'}, 'position': {'id': 1, 'name': 'Goalkeeper'}, 'teammate': False}, {'location': [108.0, 44.0], 'player': {'id': 5254, 'name': 'Ali Gabr'}, 'position': {'id': 3, 'name': 'Right Center Back'}, 'teammate': False}, {'location': [106.0, 39.0], 'player': {'id': 5250, 'name': 'Ahmed Fathy Abdel Meneim Ibrahim'}, 'position': {'id': 2, 'name': 'Right Back'}, 'teammate': False}, {'location': [94.0, 30.0], 'player': {'id': 5253, 'name': 'Amr Medhat Warda'}, 'position': {'id': 17, 'name': 'Right Wing'}, 'teammate': False}, {'location': [93.0, 54.0], 'player': {'id': 5716, 'name': 'Hussain Al Mogahwi'}, 'position': {'id': 15, 'name': 'Left Center Midfield'}, 'teammate': True}, {'location': [105.0, 51.0], 'player': {'id': 5187, 'name': 'Salem Mohammed Al Dawsari'}, 'position': {'id': 19, 'name': 'Center Attacking Midfield'}, 'teammate': True}, {'location': [94.0, 70.0], 'player': {'id': 5191, 'name': 'Mohammed Al Burayk'}, 'position': {'id': 2, 'name': 'Right Back'}, 'teammate': True}, {'location': [105.0, 70.0], 'player': {'id': 5192, 'name': 'Yehya Sulaiman Ali Al-Shehri'}, 'position': {'id': 13, 'name': 'Right Center Midfield'}, 'teammate': True}, {'location': [104.0, 39.0], 'player': {'id': 5176, 'name': 'Mohanad Aseri Abu Radiah'}, 'position': {'id': 23, 'name': 'Center Forward'}, 'teammate': True}, {'location': [90.0, 28.0], 'player': {'id': 5183, 'name': 'Yasir Gharsan Al Shahrani'}, 'position': {'id': 6, 'name': 'Left Back'}, 'teammate': True}]"
 "[{'location': [112.0, 52.0], 'player': {'id': 5262, 'name': 'Tarek Hamed'}, 'position': {'id': 15, 'name': 'Left Center Midfield'}, 'teammate': False}, {'location': [118.0, 48.0], 'player': {'id': 5254, 'name': 'Ali Gabr'}, 'position': {'id': 3, 'name': 'Right Center Back'}, 'teammate': False}, {'location': [102.0, 42.0], 'player': {'id': 5257, 'name': 'Mahmoud Abdul Monem Abdelhamid Soliman'}, 'position': {'id': 24, 'name': 'Left Center Forward'}, 'teammate': False}, {'location': [110.0, 62.0], 'player': {'id': 4063, 'name': 'Ahmed Elsayed Ali Elsayed Hegazy'}, 'position': {'id': 5, 'name': 'Left Center Back'}, 'teammate': False}, {'location': [111.0, 35.0], 'player': {'id': 5253, 'name': 'Amr Medhat Warda'}, 'position': {'id': 17, 'name': 'Right Wing'}, 'teammate': False}, {'location': [115.0, 42.0], 'player': {'id': 5250, 'name': 'Ahmed Fathy Abdel Meneim Ibrahim'}, 'position': {'id': 2, 'name': 'Right Back'}, 'teammate': False}, {'location': [114.0, 49.0], 'player': {'id': 3568, 'name': 'Mohamed Naser Elsayed Elneny'}, 'position': {'id': 13, 'name': 'Right Center Midfield'}, 'teammate': False}, {'location': [115.0, 54.0], 'player': {'id': 5263, 'name': 'Mohamed Abdul Shafy Sayed Abouezeid'}, 'position': {'id': 6, 'name': 'Left Back'}, 'teammate': False}, {'location': [120.0, 45.0], 'player': {'id': 6292, 'name': 'Essam Kamal Tawfik El Hadary'}, 'position': {'id': 1, 'name': 'Goalkeeper'}, 'teammate': False}, {'location': [116.0, 66.0], 'player': {'id': 5191, 'name': 'Mohammed Al Burayk'}, 'position': {'id': 2, 'name': 'Right Back'}, 'teammate': True}, {'location': [100.0, 36.0], 'player': {'id': 5178, 'name': 'Salman Mohammed Al Faraj'}, 'position': {'id': 21, 'name': 'Left Wing'}, 'teammate': True}, {'location': [111.0, 51.0], 'player': {'id': 5173, 'name': 'Abdullah Ibrahim Otayf'}, 'position': {'id': 10, 'name': 'Center Defensive Midfield'}, 'teammate': True}, {'location': [108.0, 41.0], 'player': {'id': 5176, 'name': 'Mohanad Aseri Abu Radiah'}, 'position': {'id': 23, 'name': 'Center Forward'}, 'teammate': True}, {'location': [103.0, 27.0], 'player': {'id': 5183, 'name': 'Yasir Gharsan Al Shahrani'}, 'position': {'id': 6, 'name': 'Left Back'}, 'teammate': True}, {'location': [110.0, 35.0], 'player': {'id': 5716, 'name': 'Hussain Al Mogahwi'}, 'position': {'id': 15, 'name': 'Left Center Midfield'}, 'teammate': True}, {'location': [116.0, 48.0], 'player': {'id': 5192, 'name': 'Yehya Sulaiman Ali Al-Shehri'}, 'position': {'id': 13, 'name': 'Right Center Midfield'}, 'teammate': True}]"]

Column: shot_key_pass_id
[nan 'edff11c8-a899-4562-bc64-a1f583690d88'
 'b300bd9d-9b54-45a0-bd6c-1a34dbf96e1c' ...
 'ceb14b8c-9a17-4f04-b998-52bc22973971'
 '2374b188-5cee-4635-83fe-4cbbbbf9ba54'
 '10507f7e-7b42-4be5-ab60-8f939889b605']

Column: shot_open_goal
[nan True]

Column: shot_outcome
[nan 'Saved' 'Blocked' 'Off T' 'Goal' 'Wayward' 'Post']

Column: shot_statsbomb_xg
[       nan 0.00981611 0.03820353 ... 0.08890756 0.02032534 0.02102943]

Column: shot_technique
[nan 'Normal' 'Volley' 'Diving Header' 'Half Volley' 'Lob' 'Overhead Kick'
 'Backheel']

Column: shot_type
[nan 'Free Kick' 'Open Play' 'Penalty']

Column: substitution_outcome
[nan 'Tactical' 'Injury']

Column: substitution_outcome_id
[ nan 103. 102.]

Column: team
['Colombia' 'England' 'Belgium' 'Sweden' 'Switzerland' 'Iran' 'Portugal'
 'Morocco' 'Croatia' 'Panama' 'Serbia' 'Brazil' 'Costa Rica' 'Egypt'
 'Uruguay' 'South Korea' 'Mexico' 'Saudi Arabia' 'Poland' 'France' 'Peru'
 'Senegal' 'Spain' 'Germany' 'Tunisia' 'Argentina' 'Denmark' 'Nigeria'
 'Iceland' 'Australia' 'Russia' 'Japan']

Column: team_id
[769 768 782 790 773 797 780 788 785 798 786 781 795 774 783 791 794 799
 789 771 784 787 772 770 777 779 776 775 793 792 796 778]

Column: timestamp
['00:00:00.000' '00:00:00.240' '00:00:02.120' ... '00:35:26.800'
 '00:51:37.840' '00:50:33.160']

Column: type
['Starting XI' 'Half Start' 'Pass' 'Ball Receipt*' 'Carry' 'Pressure'
 'Ball Recovery' 'Miscontrol' 'Camera On' '50/50' 'Clearance'
 'Foul Committed' 'Foul Won' 'Dribble' 'Duel' 'Shot' 'Goal Keeper'
 'Interception' 'Block' 'Dribbled Past' 'Dispossessed' 'Bad Behaviour'
 'Injury Stoppage' 'Player Off' 'Player On' 'Half End' 'Substitution'
 'Tactical Shift' 'Camera off' 'Shield' 'Referee Ball-Drop' 'Error'
 'Offside' 'Own Goal For' 'Own Goal Against']

Column: under_pressure
[nan True]

Column: block_save_block
[nan True]

Column: dribble_overrun
[nan True]

Column: foul_committed_offensive
[nan True]

Column: injury_stoppage_in_chain
[nan True]

Column: pass_cut_back
[nan True]

Column: pass_technique
[nan 'Through Ball']

Column: pass_through_ball
[nan True]

Column: shot_one_on_one
[nan True]

Column: ball_recovery_offensive
[nan True]

Column: miscontrol_aerial_won
[nan True]

Column: pass_miscommunication
[nan True]

Column: shot_redirect
[nan True]

### Columns to consider:
- goalkeeper_end_location
- goalkeeper_position
- goalkeeper_technique
- location
- period
- position
- shot_body_part
- shot_first_time
- shot_technique
- under_pressure
- shot_one_on_one
<br><br>
- **shot_type** (Open Play)
- **shot_outcome** (Goal)
- **shot_statsbomb_xg**

In [18]:
events_df["under_pressure"] = events_df.apply(lambda row: 1 if row["under_pressure"]==True else 0, axis=1)
events_df["under_pressure"].unique()

array([0, 1], dtype=int64)

In [19]:
events_df["goal"] = events_df.apply(lambda row:1 if row['shot_outcome']=='Goal' else 0, axis=1)
events_df["goal"].unique()

array([0, 1], dtype=int64)

In [20]:
events_df["shot_first_time"] = events_df.apply(lambda row:1 if row['shot_first_time']==True else 0, axis=1)
events_df["shot_first_time"].unique()

array([0, 1], dtype=int64)

In [21]:
events_df["shot_one_on_one"] = events_df.apply(lambda row:1 if row['shot_one_on_one']==True else 0, axis=1)
events_df["shot_one_on_one"].unique()

array([0, 1], dtype=int64)

In [22]:
round(events_df.groupby("shot_type")[["goal"]].sum()/events_df.groupby("shot_type")[["goal"]].count()*100,2).applymap(lambda x: f"{x}%")

             goal
shot_type
Free Kick   7.32%
Open Play   8.29%
Penalty    70.59%

In [23]:
round(events_df.groupby("shot_body_part")[["goal"]].sum()/events_df.groupby("shot_body_part")[["goal"]].count()*100,2).applymap(lambda x: f"{x}%")

                  goal
shot_body_part
Head            10.32%
Left Foot         9.4%
Other            7.14%
Right Foot      11.68%

In [24]:
round(events_df.groupby("shot_technique")[["goal"]].sum()/events_df.groupby("shot_technique")[["goal"]].count()*100,2).applymap(lambda x: f"{x}%")

                  goal
shot_technique
Backheel        16.67%
Diving Header    8.33%
Half Volley      7.63%
Lob             45.45%
Normal          10.99%
Overhead Kick     0.0%
Volley           8.55%

**Consider only Open Play because Penalties have much higher chance of scoring.**

In [25]:
sample = events_df[events_df["shot_type"]=="Open Play"].reset_index()

In [26]:
sample[['x', 'y']] = (sample['location'].str.strip('[]').str.split(',', expand=True).astype(float))
sample[['x','y']]

          x     y
0     112.0  54.0
1      98.0  37.0
2     119.0  36.0
3      97.0  56.0
4      90.0  18.0
...     ...   ...
1551   98.0  51.0
1552  102.0  22.0
1553  116.0  30.0
1554  101.0  58.0
1555  116.0  53.0

[1556 rows x 2 columns]

In [27]:
from mplsoccer import VerticalPitch

# visualizing shots

# filter goals / non-shot goals
df_goals = sample[sample["shot_outcome"] == 'Goal'].copy()
df_non_goal_shots = sample[sample["shot_outcome"] != 'Goal'].copy()

# setup the pitch
pitch = VerticalPitch(pad_bottom=0.5,  # pitch extends slightly below halfway line
                      half=True,  # half of a pitch
                      goal_type='box',
                      goal_alpha=0.8, pitch_color='#22312b', line_color='#c7d5cc')  # control the goal transparency

fig, ax = pitch.draw(figsize=(8, 6))

sc1 = pitch.scatter(df_non_goal_shots["x"], df_non_goal_shots["y"],
                    c='#ba4f45',
                    marker='o',
                    ax=ax)
sc2 = pitch.scatter(df_goals["x"], df_goals["y"],
                    c='#ad993c',
                    marker='o',
                    ax=ax)

# 3. Feature Engineering

In [28]:
import numpy as np
import math

def angle(x, y):
  # 44 and 36 is the location of each goal post
  g0 = [120, 44]
  p = [x, y]
  g1 = [120, 36]

  v0 = np.array(g0) - np.array(p)
  v1 = np.array(g1) - np.array(p)

  angle = np.math.atan2(np.linalg.det([v0,v1]),np.dot(v0,v1))
  return(abs(np.degrees(angle)))

def distance(x, y):
    # center of goal midpoint between 36 and 44
    x_dist = 120 - x
    y_dist = 40 - y
    
    return math.sqrt(x_dist**2 + y_dist**2)

In [29]:
sample["angle"] = sample.apply(lambda row: angle(row["x"],row["y"]), axis=1)
sample["distance"] = sample.apply(lambda row: distance(row["x"],row["y"]), axis=1)

In [30]:
train_sample = sample[["angle","distance","period","under_pressure","shot_first_time","shot_one_on_one","position",
                       "shot_body_part","shot_technique","shot_statsbomb_xg","goal"]]
train_sample_X = train_sample[["angle","distance","period","under_pressure","shot_first_time","shot_one_on_one","position",
                               "shot_body_part","shot_technique"]]
train_sample_y = train_sample[["goal"]]

In [31]:
train_sample_X = pd.get_dummies(train_sample_X, columns = ["shot_body_part"])
train_sample_X = pd.get_dummies(train_sample_X, columns = ["shot_technique"])
train_sample_X = pd.get_dummies(train_sample_X, columns = ["position"])
train_sample_X = pd.get_dummies(train_sample_X, columns = ["period"])
train_sample_X

,angle,distance,under_pressure,shot_first_time,shot_one_on_one,shot_body_part_Head,shot_body_part_Left Foot,shot_body_part_Other,shot_body_part_Right Foot,shot_technique_Backheel,...,position_Right Center Midfield,position_Right Defensive Midfield,position_Right Midfield,position_Right Wing,position_Right Wing Back,position_Secondary Striker,period_1,period_2,period_3,period_4
0,14.697319,16.124515,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,1,0,0,0
1,20.252686,22.203603,1,0,0,0,0,0,1,0,...,0,0,0,0,0,0,1,0,0,0
2,82.874984,4.123106,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
3,13.456275,28.017851,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,1,0,0,0
4,9.950627,37.202150,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1551,16.636753,24.596748,0,0,0,0,0,0,1,0,...,1,0,0,0,0,0,0,1,0,0
1552,12.835609,25.455844,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,1,0,0
1553,17.744672,10.770330,0,1,0,0,0,0,1,0,...,0,0,0,0,0,0,0,1,0,0
1554,12.800564,26.172505,1,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,1,0,0
1555,10.721969,13.601471,0,1,0,0,0,0,1,0,...,0,0,0,0,0,0,0,1,0,0

In [32]:
train_sample = pd.get_dummies(train_sample, columns = ["shot_body_part"])
train_sample = pd.get_dummies(train_sample, columns = ["shot_technique"])
train_sample = pd.get_dummies(train_sample, columns = ["position"])
train_sample = pd.get_dummies(train_sample, columns = ["period"])
train_sample.groupby(["goal"]).mean().T

goal                                        0          1
angle                               24.291690  42.781434
distance                            19.434957  12.282136
under_pressure                       0.217239   0.147287
shot_first_time                      0.220743   0.325581
shot_one_on_one                      0.027330   0.124031
shot_statsbomb_xg                    0.079865   0.252734
shot_body_part_Head                  0.194814   0.248062
shot_body_part_Left Foot             0.299229   0.294574
shot_body_part_Other                 0.009110   0.007752
shot_body_part_Right Foot            0.496847   0.449612
shot_technique_Backheel              0.003504   0.007752
shot_technique_Diving Header         0.007708   0.007752
shot_technique_Half Volley           0.076384   0.069767
shot_technique_Lob                   0.004205   0.038760
shot_technique_Normal                0.824107   0.798450
shot_technique_Overhead Kick         0.009110   0.000000
shot_technique_Volley                0.074982   0.077519
position_Center Attacking Midfield   0.055361   0.069767
position_Center Back                 0.011212   0.015504
position_Center Defensive Midfield   0.020322   0.007752
position_Center Forward              0.136650   0.209302
position_Center Midfield             0.004905   0.000000
position_Goalkeeper                  0.000701   0.000000
position_Left Attacking Midfield     0.011913   0.015504
position_Left Back                   0.043448   0.015504
position_Left Center Back            0.044849   0.062016
position_Left Center Forward         0.046952   0.077519
position_Left Center Midfield        0.071479   0.031008
position_Left Defensive Midfield     0.020322   0.000000
position_Left Midfield               0.056062   0.031008
position_Left Wing                   0.107919   0.100775
position_Left Wing Back              0.005606   0.007752
position_Right Attacking Midfield    0.009110   0.015504
position_Right Back                  0.030133   0.054264
position_Right Center Back           0.046952   0.054264
position_Right Center Forward        0.050456   0.062016
position_Right Center Midfield       0.060266   0.023256
position_Right Defensive Midfield    0.016118   0.023256
position_Right Midfield              0.041345   0.046512
position_Right Wing                  0.087596   0.062016
position_Right Wing Back             0.005606   0.007752
position_Secondary Striker           0.014716   0.007752
period_1                             0.449895   0.333333
period_2                             0.519972   0.643411
period_3                             0.012614   0.007752
period_4                             0.017519   0.015504

In [33]:
import matplotlib.pyplot as plt
import seaborn as sns
plt.figure(figsize=(30, 20))
sns.heatmap(train_sample_X.corr(), annot=True, fmt=".2f", cmap='coolwarm')
plt.show()

# 4. Model Development

In [34]:
from sklearn.preprocessing import StandardScaler
numeric_cols = ["angle", "distance"]
scaler = StandardScaler()
train_sample_X[numeric_cols] = scaler.fit_transform(train_sample_X[numeric_cols])

In [35]:
from sklearn.linear_model import LogisticRegression
from sklearn import metrics
LogRegModel = LogisticRegression()
LogRegModel.fit(train_sample_X, train_sample_y)
y_pred = LogRegModel.predict_proba(train_sample_X)[:, 1]
metrics.r2_score(train_sample_y, y_pred)

0.15578823363380645

Standardization R2: 0.15578823363380645

No standardization R2: 0.15598483135318297

Previous R2: 0.12877920747510807

In [36]:
metrics.r2_score(train_sample_y, train_sample["shot_statsbomb_xg"])

0.16097825474300864

In [37]:
sample_with_xg = train_sample_X.copy()
sample_with_xg["xG_pred"] = y_pred

In [38]:
corr = sample_with_xg[[col for col in sample_with_xg.columns if col != "xG_pred"]].corrwith(sample_with_xg["xG_pred"])
corr_df = corr.to_frame(name='xG').T
plt.figure(figsize=(30, 0.7))
sns.heatmap(corr_df, annot=True, fmt=".2f", cmap='coolwarm')
plt.xticks(fontweight='bold')
plt.yticks(fontweight='bold')
plt.show()

In [39]:
from xgboost import XGBClassifier
xgb_model = XGBClassifier(
    objective='binary:logistic',  # output = probability of class 1
    eval_metric='logloss',        # common for probabilistic models
    use_label_encoder=False,
    n_estimators=200,             # number of trees
    learning_rate=0.05,
    max_depth=4,
    subsample=0.8,
    colsample_bytree=0.8,
    random_state=42
)

xgb_model.fit(train_sample_X, train_sample_y)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=0.8, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric='logloss',
              feature_types=None, feature_weights=None, gamma=None,
              grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=0.05, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=4, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=200, n_jobs=None,
              num_parallel_tree=None, ...)

In [40]:
y_pred_xgb = xgb_model.predict_proba(train_sample_X)[:, 1]
print("R²:", metrics.r2_score(train_sample_y, y_pred_xgb))

R²: 0.3529688322825669

In [41]:
import matplotlib.pyplot as plt
from xgboost import plot_importance

plot_importance(xgb_model, max_num_features=10)
plt.show()

In [42]:
sample_with_xg = train_sample_X.copy()
sample_with_xg["xG_pred"] = y_pred_xgb

### Scale up: Load other competitions

In [43]:
competitions[(competitions["competition_id"].isin([43,55,35,16,2,11,7])) & (competitions["season_name"]>="2010")]

,competition_id,season_id,country_name,competition_name,competition_gender,competition_youth,competition_international,season_name,match_updated,match_updated_360,match_available_360,match_available
3,16,4,Europe,Champions League,male,False,False,2018/2019,2025-05-08T15:10:50.835274,2021-06-13T16:17:31.694,None,2025-05-08T15:10:50.835274
4,16,1,Europe,Champions League,male,False,False,2017/2018,2024-02-13T02:35:28.134882,2021-06-13T16:17:31.694,None,2024-02-13T02:35:28.134882
5,16,2,Europe,Champions League,male,False,False,2016/2017,2024-02-13T02:37:32.205154,2021-06-13T16:17:31.694,None,2024-02-13T02:37:32.205154
6,16,27,Europe,Champions League,male,False,False,2015/2016,2024-06-12T07:45:38.786894,2021-06-13T16:17:31.694,None,2024-06-12T07:45:38.786894
7,16,26,Europe,Champions League,male,False,False,2014/2015,2024-02-12T12:49:54.914228,2021-06-13T16:17:31.694,None,2024-02-12T12:49:54.914228
8,16,25,Europe,Champions League,male,False,False,2013/2014,2024-02-12T12:48:48.479157,2021-06-13T16:17:31.694,None,2024-02-12T12:48:48.479157
9,16,24,Europe,Champions League,male,False,False,2012/2013,2024-02-12T12:47:34.340413,2021-06-13T16:17:31.694,None,2024-02-12T12:47:34.340413
10,16,23,Europe,Champions League,male,False,False,2011/2012,2024-02-13T02:36:35.698340,2021-06-13T16:17:31.694,None,2024-02-13T02:36:35.698340
11,16,22,Europe,Champions League,male,False,False,2010/2011,2024-02-12T12:53:03.944320,2021-06-13T16:17:31.694,None,2024-02-12T12:53:03.944320
29,43,106,International,FIFA World Cup,male,False,True,2022,2024-12-16T10:15:11.055845,2024-12-16T10:21:13.710934,2024-12-16T10:21:13.710934,2024-12-16T10:15:11.055845
30,43,3,International,FIFA World Cup,male,False,True,2018,2024-06-12T07:38:19.345758,2021-06-13T16:17:31.694,None,2024-06-12T07:38:19.345758
38,11,90,Spain,La Liga,male,False,False,2020/2021,2025-01-29T17:39:28.924386,2025-01-29T18:09:18.620699,2025-01-29T18:09:18.620699,2025-01-29T17:39:28.924386
39,11,42,Spain,La Liga,male,False,False,2019/2020,2024-12-16T16:51:06.833054,2021-06-13T16:17:31.694,None,2024-12-16T16:51:06.833054
40,11,4,Spain,La Liga,male,False,False,2018/2019,2024-09-22T18:50:23.364757,2021-07-09T14:53:22.103024,None,2024-09-22T18:50:23.364757
41,11,1,Spain,La Liga,male,False,False,2017/2018,2025-07-14T10:01:16.674864,2021-06-13T16:17:31.694,None,2025-07-14T10:01:16.674864
42,11,2,Spain,La Liga,male,False,False,2016/2017,2025-03-09T16:03:54.962718,2021-06-13T16:17:31.694,None,2025-03-09T16:03:54.962718
43,11,27,Spain,La Liga,male,False,False,2015/2016,2025-04-23T13:59:22.835792,2021-06-13T16:17:31.694,None,2025-04-23T13:59:22.835792
44,11,26,Spain,La Liga,male,False,False,2014/2015,2025-06-24T13:39:01.068680,2021-06-13T16:17:31.694,None,2025-06-24T13:39:01.068680
45,11,25,Spain,La Liga,male,False,False,2013/2014,2025-06-24T09:52:44.048585,2021-06-13T16:17:31.694,None,2025-06-24T09:52:44.048585
46,11,24,Spain,La Liga,male,False,False,2012/2013,2025-06-24T13:53:14.047130,2021-06-13T16:17:31.694,None,2025-06-24T13:53:14.047130
47,11,23,Spain,La Liga,male,False,False,2011/2012,2025-06-24T13:38:10.764259,2021-06-13T16:17:31.694,None,2025-06-24T13:38:10.764259
48,11,22,Spain,La Liga,male,False,False,2010/2011,2025-06-24T13:51:54.910296,2021-06-13T16:17:31.694,None,2025-06-24T13:51:54.910296
58,7,235,France,Ligue 1,male,False,False,2022/2023,2024-12-19T13:56:45.683863,2025-06-30T02:31:32.046070,2025-06-30T02:31:32.046070,2024-12-19T13:56:45.683863
59,7,108,France,Ligue 1,male,False,False,2021/2022,2025-06-15T12:56:15.594872,2025-06-15T13:02:45.341609,2025-06-15T13:02:45.341609,2025-06-15T12:56:15.594872
60,7,27,France,Ligue 1,male,False,False,2015/2016,2024-12-16T08:48:23.066123,None,None,2024-12-16T08:48:23.066123
64,2,27,England,Premier League,male,False,False,2015/2016,2025-04-23T14:36:29.347042,2021-06-13T16:17:31.694,None,2025-04-23T14:36:29.347042
68,55,282,Europe,UEFA Euro,male,False,True,2024,2024-09-28T16:51:20.698794,2025-03-24T14:12:30.785094,2025-03-24T14:12:30.785094,2024-09-28T16:51:20.698794
69,55,43,Europe,UEFA Euro,male,False,True,2020,2024-07-31T12:29:15.702309,2024-07-31T12:30:57.587087,2024-07-31T12:30:57.587087,2024-07-31T12:29:15.702309

import os
import glob
from datetime import datetime

start = datetime.now()

competitions_filtered = competitions[
    (competitions["competition_id"].isin([43, 55, 35, 16, 2, 11, 12, 9, 7])) & (competitions["season_name"] >= "2010")]
desired_cols = ["location", "period", "under_pressure", "shot_first_time","shot_one_on_one", "position", "shot_body_part",
                "shot_technique","shot_statsbomb_xg", "shot_outcome","shot_type","team","player"]
batch_num = 0
all_events = []
for _, row in competitions_filtered.iterrows():
    comp_id = row["competition_id"]
    season_id = row["season_id"]
    matches = sb.matches(competition_id=comp_id, season_id=season_id)

    for match_id in matches["match_id"]:
        events = sb.events(match_id=match_id)
        existing_cols = [col for col in desired_cols if col in events.columns]
        events = events[existing_cols]
        events["match_id"] = match_id
        events["competition_id"] = comp_id
        events["season_id"] = season_id
        all_events.append(events)

        if len(all_events) >= 50:
            batch = pd.concat(all_events, ignore_index=True)
            batch_num += 1
            batch.to_parquet(f"events_batch_{batch_num}.parquet", index=False)
            all_events = []

files = glob.glob("events_batch_*.parquet")
events_all = pd.concat([pd.read_parquet(f) for f in files], ignore_index=True)
events_all.to_parquet("events_all.parquet", index=False)
           
end = datetime.now()
print("Duration:", end - start, "h")

In [44]:
events_all = pd.read_parquet("events_all.parquet")
events_all

,location,period,under_pressure,shot_first_time,shot_one_on_one,position,shot_body_part,shot_technique,shot_statsbomb_xg,shot_outcome,shot_type,team,player,match_id,competition_id,season_id
0,None,1,None,None,None,None,None,None,NaN,None,None,Bayer Leverkusen,None,3895302,9,281
1,None,1,None,None,None,None,None,None,NaN,None,None,Werder Bremen,None,3895302,9,281
2,None,1,None,None,None,None,None,None,NaN,None,None,Bayer Leverkusen,None,3895302,9,281
3,None,1,None,None,None,None,None,None,NaN,None,None,Werder Bremen,None,3895302,9,281
4,None,2,None,None,None,None,None,None,NaN,None,None,Bayer Leverkusen,None,3895302,9,281
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8790985,None,2,None,None,None,Left Defensive Midfield,None,None,NaN,None,None,Japan,Gaku Shibasaki,7584,43,3
8790986,None,2,None,None,None,Right Wing,None,None,NaN,None,None,Japan,Genki Haraguchi,7584,43,3
8790987,"[117.0, 16.0]",2,True,None,None,Right Center Midfield,None,None,NaN,None,None,Belgium,Kevin De Bruyne,7584,43,3
8790988,"[113.0, 41.0]",2,None,None,None,Right Attacking Midfield,None,None,NaN,None,None,Belgium,Marouane Fellaini-Bakkioui,7584,43,3
8790989,"[10.0, 52.0]",2,None,None,None,Left Center Midfield,None,None,NaN,None,None,Belgium,Axel Witsel,7584,43,3

In [45]:
events_all.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8790990 entries, 0 to 8790989
Data columns (total 16 columns):
 #   Column             Dtype
---  ------             -----
 0   location           object
 1   period             int64
 2   under_pressure     object
 3   shot_first_time    object
 4   shot_one_on_one    object
 5   position           object
 6   shot_body_part     object
 7   shot_technique     object
 8   shot_statsbomb_xg  float64
 9   shot_outcome       object
 10  shot_type          object
 11  team               object
 12  player             object
 13  match_id           int64
 14  competition_id     int64
 15  season_id          int64
dtypes: float64(1), int64(4), object(11)
memory usage: 1.0+ GB

In [46]:
from sklearn.model_selection import train_test_split
events_all = events_all[events_all["location"].notna()]
sample = events_all[events_all["shot_type"]=="Open Play"].reset_index()
sample["goal"] = sample.apply(lambda row:1 if row['shot_outcome']=='Goal' else 0, axis=1)
sample["under_pressure"] = sample.apply(lambda row: 1 if row["under_pressure"]==True else 0, axis=1)
sample["shot_first_time"] = sample.apply(lambda row:1 if row['shot_first_time']==True else 0, axis=1)
sample["shot_one_on_one"] = sample.apply(lambda row:1 if row['shot_one_on_one']==True else 0, axis=1)
sample[['x', 'y']] = pd.DataFrame(sample['location'].tolist(), index=sample.index)
sample["angle"] = sample.apply(lambda row: angle(row["x"],row["y"]), axis=1)
sample["distance"] = sample.apply(lambda row: distance(row["x"],row["y"]), axis=1)
train_sample = sample[["angle","distance","period","under_pressure","shot_first_time","shot_one_on_one","position",
                       "shot_body_part","shot_technique","shot_statsbomb_xg","goal"]]
X = train_sample.drop(["shot_statsbomb_xg","goal"], axis=1)
y = train_sample["goal"]
categorical_cols = ["shot_body_part", "shot_technique", "position", "period"]
X = pd.get_dummies(X, columns=categorical_cols)
train_sample = pd.get_dummies(train_sample, columns=categorical_cols)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, stratify=y, random_state=42)

In [47]:
train_sample.groupby(["goal"]).mean().T

goal                                        0          1
angle                               23.931080  39.378069
distance                            19.520393  12.586994
under_pressure                       0.266356   0.236376
shot_first_time                      0.318226   0.449300
shot_one_on_one                      0.046192   0.131095
shot_statsbomb_xg                    0.079137   0.265531
shot_body_part_Head                  0.168334   0.173275
shot_body_part_Left Foot             0.323401   0.316349
shot_body_part_Other                 0.002433   0.008267
shot_body_part_Right Foot            0.505832   0.502109
shot_technique_Backheel              0.003978   0.004387
shot_technique_Diving Header         0.003630   0.008267
shot_technique_Half Volley           0.148830   0.144761
shot_technique_Lob                   0.009057   0.024633
shot_technique_Normal                0.759250   0.725831
shot_technique_Overhead Kick         0.006141   0.005736
shot_technique_Volley                0.069114   0.086384
position_Center Attacking Midfield   0.067724   0.070187
position_Center Back                 0.005002   0.004218
position_Center Defensive Midfield   0.022130   0.009617
position_Center Forward              0.152653   0.229796
position_Center Midfield             0.000154   0.000000
position_Goalkeeper                  0.000154   0.000000
position_Left Attacking Midfield     0.005214   0.007086
position_Left Back                   0.036575   0.017716
position_Left Center Back            0.036034   0.031719
position_Left Center Forward         0.059188   0.082673
position_Left Center Midfield        0.054843   0.032563
position_Left Defensive Midfield     0.041519   0.020752
position_Left Midfield               0.041306   0.032732
position_Left Wing                   0.097926   0.110849
position_Left Wing Back              0.009617   0.007255
position_Right Attacking Midfield    0.005755   0.005568
position_Right Back                  0.035436   0.021259
position_Right Center Back           0.038332   0.037793
position_Right Center Forward        0.058532   0.071706
position_Right Center Midfield       0.050479   0.042180
position_Right Defensive Midfield    0.039491   0.023452
position_Right Midfield              0.039124   0.030032
position_Right Wing                  0.091804   0.101400
position_Right Wing Back             0.010486   0.009111
position_Secondary Striker           0.000521   0.000337
period_1                             0.456570   0.440020
period_2                             0.539935   0.558293
period_3                             0.001661   0.000506
period_4                             0.001835   0.001181

In [48]:
plt.figure(figsize=(30, 20))
sns.heatmap(X_train.corr(), annot=True, fmt=".2f", cmap='coolwarm')
plt.show()

In [49]:
X_train[numeric_cols] = scaler.fit_transform(X_train[numeric_cols])
X_test[numeric_cols] = scaler.transform(X_test[numeric_cols])
LogRegModel = LogisticRegression()
LogRegModel.fit(X_train, y_train)
y_pred = LogRegModel.predict_proba(X_test)[:, 1]
metrics.r2_score(y_test, y_pred)

0.15340847416536008

In [50]:
metrics.r2_score(y_test, X_test.join(train_sample["shot_statsbomb_xg"])["shot_statsbomb_xg"])

0.20811368087993742

In [51]:
from sklearn.metrics import roc_auc_score, average_precision_score, log_loss, brier_score_loss
print("ROC-AUC:", roc_auc_score(y_test, y_pred))
print("PR-AUC:", average_precision_score(y_test, y_pred))
print("Log Loss:", log_loss(y_test, y_pred))
print("Brier Score:", brier_score_loss(y_test, y_pred))
print("xG Sum / Goals Ratio:", y_pred.sum() / y_test.sum())

ROC-AUC: 0.7937066520669729
PR-AUC: 0.37548861370483266
Log Loss: 0.27227344068116616
Brier Score: 0.0779885386661362
xG Sum / Goals Ratio: 1.0025027178487276

In [52]:
sample_with_xg = X_test.copy()
sample_with_xg["xG_pred"] = y_pred

In [53]:
corr = sample_with_xg[[col for col in sample_with_xg.columns if col != "xG_pred"]].corrwith(sample_with_xg["xG_pred"])
corr_df = corr.to_frame(name='xG').T
plt.figure(figsize=(30, 0.7))
sns.heatmap(corr_df, annot=True, fmt=".2f", cmap='coolwarm')
plt.xticks(fontweight='bold')
plt.yticks(fontweight='bold')
plt.show()

In [54]:
xgb_model = XGBClassifier(
    objective='binary:logistic',  # output = probability of class 1
    eval_metric='logloss',        # common for probabilistic models
    use_label_encoder=False,
    n_estimators=200,             # number of trees
    learning_rate=0.05,
    max_depth=4,
    subsample=0.8,
    colsample_bytree=0.8,
    random_state=42
)

xgb_model.fit(X_train, y_train)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=0.8, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric='logloss',
              feature_types=None, feature_weights=None, gamma=None,
              grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=0.05, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=4, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=200, n_jobs=None,
              num_parallel_tree=None, ...)

In [55]:
y_pred_xgb = xgb_model.predict_proba(X_test)[:, 1]
print("R²:", metrics.r2_score(y_test, y_pred_xgb))

R²: 0.15708439233170923

In [56]:
print("ROC-AUC:", roc_auc_score(y_test, y_pred_xgb))
print("PR-AUC:", average_precision_score(y_test, y_pred_xgb))
print("Log Loss:", log_loss(y_test, y_pred_xgb))
print("Brier Score:", brier_score_loss(y_test, y_pred_xgb))
print("xG Sum / Goals Ratio:", y_pred_xgb.sum() / y_test.sum())

ROC-AUC: 0.7957407918867415
PR-AUC: 0.3769376825192118
Log Loss: 0.27102167067580385
Brier Score: 0.07764991079507733
xG Sum / Goals Ratio: 0.9979902178929325

In [57]:
plot_importance(xgb_model, max_num_features=10)
plt.show()

In [58]:
sample_with_xg = X_test.copy()
sample_with_xg["xG_pred"] = y_pred_xgb

# 5. Evaluation

In [59]:
X[numeric_cols] = scaler.fit_transform(X[numeric_cols])
xG_all = LogRegModel.predict_proba(X)[:, 1]
xGb_all = xgb_model.predict_proba(X)[:, 1]
data_xG = X.copy()
data_xG["goal"] = y
data_xG["xG_LogReg"] =xG_all
data_xG["xG_xGBoost"] = xGb_all

In [60]:
data_xG = data_xG.join(sample[["shot_statsbomb_xg","team","match_id","competition_id","season_id","player"]])
data_xG

,angle,distance,under_pressure,shot_first_time,shot_one_on_one,shot_body_part_Head,shot_body_part_Left Foot,shot_body_part_Other,shot_body_part_Right Foot,shot_technique_Backheel,...,period_4,goal,xG_LogReg,xG_xGBoost,shot_statsbomb_xg,team,match_id,competition_id,season_id,player
0,-0.239906,0.164540,0,1,0,0,0,0,1,0,...,0,0,0.082243,0.074670,0.056644,Werder Bremen,3895302,9,281,Leonardo Bittencourt
1,0.800232,-1.221804,1,1,0,0,1,0,0,0,...,0,0,0.319169,0.267144,0.143381,Bayer Leverkusen,3895302,9,281,Piero Martín Hincapié Reyna
2,-0.703725,0.255942,0,1,0,0,1,0,0,0,...,0,0,0.044723,0.026737,0.038188,Werder Bremen,3895302,9,281,Julián Malatini
3,0.463593,-1.087371,0,0,0,1,0,0,0,0,...,0,0,0.054754,0.091363,0.052781,Bayer Leverkusen,3895302,9,281,Jonathan Tah
4,-0.696439,1.426473,1,0,0,0,1,0,0,0,...,0,0,0.011939,0.011699,0.021272,Bayer Leverkusen,3895302,9,281,Granit Xhaka
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
57706,1.190134,-1.203888,1,0,0,1,0,0,0,0,...,0,0,0.102683,0.073572,0.129269,Belgium,7584,43,3,Nacer Chadli
57707,1.778533,-1.367995,0,0,0,1,0,0,0,0,...,0,0,0.163837,0.175380,0.204527,Belgium,7584,43,3,Romelu Lukaku Menama
57708,-0.909751,2.505640,0,0,0,0,0,0,1,0,...,0,0,0.003396,0.005284,0.006300,Belgium,7584,43,3,Thomas Meunier
57709,-0.790763,1.183845,0,0,0,0,1,0,0,0,...,0,0,0.014843,0.006546,0.023417,Belgium,7584,43,3,Jan Vertonghen
57710,1.204321,-1.099552,0,0,0,0,1,0,0,0,...,0,1,0.367082,0.365187,0.259712,Belgium,7584,43,3,Nacer Chadli

In [61]:
data_xG[['goal', 'shot_statsbomb_xg', 'xG_LogReg', 'xG_xGBoost']].sum()

goal                 5927.000000
shot_statsbomb_xg    5671.819937
xG_LogReg            5921.300550
xG_xGBoost           5920.309082
dtype: float64

In [62]:
data_xG.groupby('team')[['goal', 'shot_statsbomb_xg', 'xG_LogReg', 'xG_xGBoost']].sum().sort_values("goal", ascending=False)

                     goal  shot_statsbomb_xg   xG_LogReg  xG_xGBoost
team
Barcelona             895         689.937897  745.410550  745.236938
Paris Saint-Germain   214         175.999358  171.797246  175.615387
Real Madrid           133         103.099928  107.572114  106.731941
Bayer Leverkusen      123         111.570032  115.157734  115.225906
Borussia Dortmund      77          73.294296   66.325503   67.690063
...                   ...                ...         ...         ...
Córdoba CF              0           0.615977    0.796530    0.624445
Wales                   0           1.644895    2.075550    2.046999
Metz                    0           0.477597    0.613944    0.553876
Elche                   0           1.363825    1.290787    1.380828
AC Ajaccio              0           0.535568    0.695634    0.623006

[176 rows x 4 columns]

In [63]:
data_xG.groupby('player')[['goal', 'shot_statsbomb_xg', 'xG_LogReg', 'xG_xGBoost']].sum().sort_values("goal", ascending=False)

,goal,shot_statsbomb_xg,xG_LogReg,xG_xGBoost
player,,,,
Lionel Andrés Messi Cuccittini,322,218.770414,252.983366,255.660355
Luis Alberto Suárez Díaz,129,101.852185,104.006398,102.504196
Neymar da Silva Santos Junior,74,63.734701,73.532789,72.523575
Kylian Mbappé Lottin,55,39.475857,38.536989,37.686890
Pedro Eliezer Rodríguez Ledesma,45,38.626440,42.586564,41.872559
...,...,...,...,...
Manuel Jesús Arana Rodríguez,0,0.040910,0.039240,0.036322
Manuel Henrique Tavares Fernandes,0,0.047119,0.045128,0.035975
Eberechi Eze,0,0.040455,0.069255,0.048754
Manuel Castellano Castro,0,0.430936,0.299106,0.341479
Mohammed Al Burayk,0,0.379228,0.277753,0.260255

In [64]:
WC2022 = data_xG[(data_xG["competition_id"]==43) & (data_xG["season_id"]==106)]
WC2022

,angle,distance,under_pressure,shot_first_time,shot_one_on_one,shot_body_part_Head,shot_body_part_Left Foot,shot_body_part_Other,shot_body_part_Right Foot,shot_technique_Backheel,...,period_4,goal,xG_LogReg,xG_xGBoost,shot_statsbomb_xg,team,match_id,competition_id,season_id,player
55454,-0.427552,0.615941,0,1,0,0,1,0,0,0,...,0,0,0.023419,0.025358,0.036566,Switzerland,3857256,43,106,Granit Xhaka
55455,2.209499,-1.400515,0,1,0,0,1,0,0,0,...,0,0,0.410935,0.410963,0.353289,Switzerland,3857256,43,106,Breel-Donald Embolo
55456,0.121093,-0.294577,0,1,0,0,0,0,1,0,...,0,0,0.073647,0.125234,0.069527,Switzerland,3857256,43,106,Granit Xhaka
55457,1.484520,-1.224110,0,0,0,1,0,0,0,0,...,0,0,0.094376,0.134574,0.081609,Serbia,3857256,43,106,Nikola Milenković
55458,-0.596551,0.730575,0,0,0,0,1,0,0,0,...,0,0,0.033363,0.035750,0.030002,Serbia,3857256,43,106,Andrija Živković
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
56831,3.531400,-1.711934,0,0,0,1,0,0,0,0,...,0,0,0.381129,0.370509,0.568312,Denmark,3857254,43,106,Andreas Evald Cornelius
56832,-0.707238,0.562545,0,0,0,0,0,0,1,0,...,0,0,0.036351,0.023262,0.028724,Denmark,3857254,43,106,Mathias Jensen
56833,2.237457,-1.457797,1,0,0,1,0,0,0,0,...,0,0,0.174013,0.143700,0.145394,Denmark,3857254,43,106,Andreas Evald Cornelius
56834,-0.623514,0.948845,0,0,0,0,0,0,1,0,...,0,0,0.027333,0.018752,0.028684,Denmark,3857254,43,106,Joakim Mæhle
56835,0.339225,-0.696985,1,0,0,1,0,0,0,0,...,0,0,0.040558,0.033604,0.022084,Denmark,3857254,43,106,Andreas Evald Cornelius

In [65]:
WC2022[['goal', 'shot_statsbomb_xg', 'xG_LogReg', 'xG_xGBoost']].sum()

goal                 150.000000
shot_statsbomb_xg    135.884381
xG_LogReg            151.528032
xG_xGBoost           149.683563
dtype: float64

In [66]:
WC2022 = WC2022.join(sample[["x","y"]])
df_goals = WC2022[WC2022["goal"] == 1].copy()
df_non_goal_shots = WC2022[WC2022["goal"] == 0].copy()

# setup the pitch
pitch = VerticalPitch(pad_bottom=0.5,  # pitch extends slightly below halfway line
                      half=True,  # half of a pitch
                      goal_type='box',
                      goal_alpha=0.8, pitch_color='#22312b', line_color='#c7d5cc')  # control the goal transparency

fig, ax = pitch.draw(figsize=(8, 6))

sc1 = pitch.scatter(df_non_goal_shots["x"], df_non_goal_shots["y"],
                    c='#ba4f45',
                    marker='o',
                    ax=ax)
sc2 = pitch.scatter(df_goals["x"], df_goals["y"],
                    c='#ad993c',
                    marker='o',
                    ax=ax)

In [67]:
df_team = WC2022.groupby(["match_id", "team"])[["goal", "shot_statsbomb_xg", "xG_LogReg", "xG_xGBoost"]].sum().reset_index()
df_team["team_number"] = df_team.groupby("match_id").cumcount() + 1
xg_team = df_team.pivot(index="match_id", columns="team_number")
xg_team.columns = [f"{col[0]}{int(col[1])}" for col in xg_team.columns]
xg_team = xg_team.reset_index()
xg_team

,match_id,team1,team2,goal1,goal2,shot_statsbomb_xg1,shot_statsbomb_xg2,xG_LogReg1,xG_LogReg2,xG_xGBoost1,xG_xGBoost2
0,3857254,Denmark,Tunisia,0.0,0.0,1.566559,1.059935,1.470840,1.504847,1.284730,1.202709
1,3857255,Japan,Spain,2.0,1.0,1.157801,0.857712,1.230875,0.879139,0.970948,0.816922
2,3857256,Serbia,Switzerland,2.0,3.0,1.189004,3.103515,1.379405,2.729800,1.443870,2.874526
3,3857257,Australia,Denmark,1.0,0.0,0.469723,0.737155,0.423719,1.241820,0.443730,1.046114
4,3857258,Brazil,Serbia,2.0,0.0,2.060890,0.163327,1.896126,0.161351,1.840314,0.131045
...,...,...,...,...,...,...,...,...,...,...,...
59,3869486,Morocco,Portugal,1.0,0.0,0.972023,0.744121,0.929036,0.871048,0.919463,0.892935
60,3869519,Argentina,Croatia,2.0,0.0,1.080863,0.402532,1.271053,0.684371,1.238454,0.505620
61,3869552,France,Morocco,2.0,0.0,2.002449,1.230364,1.958884,1.248333,2.050494,1.211348
62,3869684,Croatia,Morocco,2.0,1.0,0.849269,0.991457,0.729100,1.193468,0.720507,1.181257
63,3869685,Argentina,France,2.0,1.0,1.974806,0.705618,2.089972,0.485401,1.949343,0.494568

In [68]:
team_form = df_team.groupby("team")[['goal', 'shot_statsbomb_xg', 'xG_LogReg', 'xG_xGBoost']].sum().sort_values("goal", ascending=False)
team_form

               goal  shot_statsbomb_xg  xG_LogReg  xG_xGBoost
team
France           14          10.181939  10.957163   11.373903
Argentina        11           9.819064  10.546004   10.829145
England          11           6.933062   7.768943    7.684911
Portugal         10           5.690164   6.228713    5.984684
Netherlands      10           4.913616   5.588052    5.382266
Spain             8           3.962028   4.841663    4.444992
Croatia           8           6.894181   7.765704    7.315103
Brazil            7           9.448559   9.982168   10.161661
Morocco           6           5.414087   5.984411    6.254718
Serbia            5           3.090398   3.257078    3.311350
Switzerland       5           6.066626   5.461470    5.786345
Japan             5           4.063704   4.682332    4.265265
Ghana             5           2.569753   3.111966    3.132893
Germany           5           7.394015   8.103163    8.103395
South Korea       5           3.546076   4.239283    3.854350
Cameroon          4           3.059733   3.023100    2.826391
Senegal           4           3.437066   4.355702    4.428031
Iran              3           3.046906   3.158990    3.362901
Ecuador           3           3.001612   3.040666    3.008126
Australia         3           1.578172   1.534015    1.650714
United States     3           3.858140   4.623299    4.210765
Saudi Arabia      3           2.278574   2.855705    2.685367
Costa Rica        2           1.234112   1.542673    1.622592
Poland            2           3.053579   3.539099    3.458210
Uruguay           2           3.227610   3.465872    3.969825
Tunisia           1           2.410452   3.298244    2.866134
Mexico            1           2.886489   3.402607    3.381099
Qatar             1           1.407992   1.544242    1.422462
Denmark           1           3.192257   3.543276    3.213025
Canada            1           3.133144   3.860351    3.604307
Belgium           1           3.687118   4.379053    4.321104
Wales             0           1.404152   1.843025    1.767520

In [69]:
team_form["diff"] = team_form["goal"]-team_form["xG_xGBoost"]
team_form.sort_values("diff", ascending=False)

               goal  shot_statsbomb_xg  xG_LogReg  xG_xGBoost      diff
team
Netherlands      10           4.913616   5.588052    5.382266  4.617734
Portugal         10           5.690164   6.228713    5.984684  4.015316
Spain             8           3.962028   4.841663    4.444992  3.555008
England          11           6.933062   7.768943    7.684911  3.315089
France           14          10.181939  10.957163   11.373903  2.626097
Ghana             5           2.569753   3.111966    3.132893  1.867107
Serbia            5           3.090398   3.257078    3.311350  1.688650
Australia         3           1.578172   1.534015    1.650714  1.349286
Cameroon          4           3.059733   3.023100    2.826391  1.173609
South Korea       5           3.546076   4.239283    3.854350  1.145650
Japan             5           4.063704   4.682332    4.265265  0.734735
Croatia           8           6.894181   7.765704    7.315103  0.684897
Costa Rica        2           1.234112   1.542673    1.622592  0.377408
Saudi Arabia      3           2.278574   2.855705    2.685367  0.314633
Argentina        11           9.819064  10.546004   10.829145  0.170855
Ecuador           3           3.001612   3.040666    3.008126 -0.008126
Morocco           6           5.414087   5.984411    6.254718 -0.254718
Iran              3           3.046906   3.158990    3.362901 -0.362901
Qatar             1           1.407992   1.544242    1.422462 -0.422462
Senegal           4           3.437066   4.355702    4.428031 -0.428031
Switzerland       5           6.066626   5.461470    5.786345 -0.786345
United States     3           3.858140   4.623299    4.210765 -1.210765
Poland            2           3.053579   3.539099    3.458210 -1.458210
Wales             0           1.404152   1.843025    1.767520 -1.767520
Tunisia           1           2.410452   3.298244    2.866134 -1.866134
Uruguay           2           3.227610   3.465872    3.969825 -1.969825
Denmark           1           3.192257   3.543276    3.213025 -2.213025
Mexico            1           2.886489   3.402607    3.381099 -2.381099
Canada            1           3.133144   3.860351    3.604307 -2.604307
Germany           5           7.394015   8.103163    8.103395 -3.103395
Brazil            7           9.448559   9.982168   10.161661 -3.161661
Belgium           1           3.687118   4.379053    4.321104 -3.321104

In [70]:
df_player = WC2022.groupby(["player"])[["goal", "shot_statsbomb_xg", "xG_LogReg", "xG_xGBoost"]].sum().reset_index().sort_values(["goal"], ascending=False)
df_player

                        player  goal  shot_statsbomb_xg  xG_LogReg  xG_xGBoost
231       Kylian Mbappé Lottin     6           2.602085   3.529043    3.651713
309             Olivier Giroud     4           3.035955   2.693565    2.728132
208             Julián Álvarez     4           1.908327   2.334444    2.315427
76           Cody Mathès Gakpo     3           0.562367   0.494801    0.600312
67                 Bukayo Saka     3           0.579455   1.137063    1.185860
..                         ...   ...                ...        ...         ...
161               Ismaïla Sarr     0           1.065290   1.346351    1.258945
160              Ismail Jakobs     0           0.014393   0.009342    0.011000
159  Ismaeel Mohammad Mohammad     0           0.357907   0.448547    0.371280
158              In-Beom Hwang     0           0.197748   0.178622    0.137516
424             İlkay Gündoğan     0           0.345454   0.345720    0.368054

[425 rows x 5 columns]

In [71]:
df_player["diff"] = df_player["goal"]-df_player["xG_xGBoost"]
df_player.sort_values("diff", ascending=False)

,player,goal,shot_statsbomb_xg,xG_LogReg,xG_xGBoost,diff
76,Cody Mathès Gakpo,3,0.562367,0.494801,0.600312,2.399688
231,Kylian Mbappé Lottin,6,2.602085,3.529043,3.651713,2.348287
67,Bukayo Saka,3,0.579455,1.137063,1.185860,1.814140
421,Álvaro Borja Morata Martín,3,1.109481,1.358027,1.232216,1.767784
327,Rafael Alexandre Conceição Leão,2,0.248384,0.296429,0.302849,1.697151
...,...,...,...,...,...,...
187,Jonathan David,0,0.812814,1.139006,1.210857,-1.210857
161,Ismaïla Sarr,0,1.065290,1.346351,1.258945,-1.258945
171,Jamal Musiala,0,1.152516,1.358513,1.495016,-1.495016
348,Romelu Lukaku Menama,0,1.684155,1.600732,1.553446,-1.553446
233,Lautaro Javier Martínez,0,2.121547,1.821827,1.961627,-1.961627

In [72]:
mbappe = WC2022[WC2022["player"].str.contains('Kylian')]
mbappe_goals = mbappe[mbappe["goal"] == 1].copy()
mbappe_non_goal_shots = mbappe[mbappe["goal"] == 0].copy()

pitch = VerticalPitch(pad_bottom=0.5, half=True, goal_type='box', goal_alpha=0.8, pitch_color='#22312b', line_color='#c7d5cc')
fig, ax = pitch.draw(figsize=(8, 6))
ax.text(80, 123, 'Kylian Mbappé Shot Map', color='white', fontsize=14, ha='right', va='top', fontweight='bold')
sc1 = pitch.scatter(mbappe_non_goal_shots["x"], mbappe_non_goal_shots["y"], c='#ba4f45', marker='o', ax=ax)
sc2 = pitch.scatter(mbappe_goals["x"], mbappe_goals["y"], c='#ad993c', marker='o', ax=ax)

# 6. Deployment

In [73]:
import joblib
joblib.dump(xgb_model, "xg_model.pkl")

['xg_model.pkl']

In [75]:
%%writefile xg_app.py
import streamlit as st
import pandas as pd
import joblib

# Load trained model
model = joblib.load("xg_model.pkl")

st.title("⚽ Expected Goals (xG) Predictor")

st.markdown("Enter shot features below to estimate the xG value:")

# Numeric inputs
distance = st.number_input("Shot Distance (meters)", min_value=0.0, max_value=100.0, value=10.0)
angle = st.number_input("Shot Angle (degrees)", min_value=0.0, max_value=180.0, value=45.0)

# Binary inputs (checkboxes)
under_pressure = st.checkbox("Under Pressure?", value=False)
shot_first_time = st.checkbox("First Time Shot?", value=False)
shot_one_on_one = st.checkbox("One-on-One with GK?", value=False)

# Body part (one-hot encoded)
body_part = st.selectbox("Body Part", ["Head", "Left Foot", "Right Foot", "Other"])

# Technique (one-hot encoded)
technique = st.selectbox( "Shot Technique", 
                         ["Normal", "Backheel", "Diving Header", "Half Volley", "Lob","Overhead Kick", "Volley"])

# Position (one-hot encoded)
position = st.selectbox(
    "Player Position",
    [
        "Goalkeeper", "Center Back", "Left Back", "Right Back",
        "Left Wing Back", "Right Wing Back",
        "Left Defensive Midfield", "Right Defensive Midfield",
        "Center Defensive Midfield",
        "Left Midfield", "Center Midfield", "Right Midfield",
        "Left Attacking Midfield", "Center Attacking Midfield", "Right Attacking Midfield",
        "Left Center Forward", "Right Center Forward", "Secondary Striker"
    ]
)

# Period (first half, second half, etc.)
period = st.selectbox("Match Period", ["1", "2", "3", "4"])

# Initialize all features to 0
features = {
    'angle': angle,
    'distance': distance,
    'under_pressure': int(under_pressure),
    'shot_first_time': int(shot_first_time),
    'shot_one_on_one': int(shot_one_on_one)
}

# Add one-hot encoded features
# Body parts
for bp in ['Head', 'Left Foot', 'Right Foot', 'Other']:
    features[f'shot_body_part_{bp}'] = 1 if body_part == bp else 0

# Techniques
for t in ['Backheel', 'Diving Header', 'Half Volley', 'Lob', 'Normal', 'Overhead Kick', 'Volley']:
    features[f'shot_technique_{t}'] = 1 if technique == t else 0

# Positions
positions = [
    "Center Attacking Midfield", "Center Back", "Center Defensive Midfield", "Center Forward", "Center Midfield",
    "Goalkeeper", "Left Attacking Midfield", "Left Back", "Left Center Forward", "Left Center Midfield",
    "Left Defensive Midfield", "Left Midfield", "Left Wing", "Left Wing Back",
    "Right Attacking Midfield", "Right Back", "Right Center Back", "Right Center Forward", "Right Center Midfield",
    "Right Defensive Midfield", "Right Midfield", "Right Wing", "Right Wing Back",
    "Secondary Striker"
]
for pos in positions:
    features[f'position_{pos}'] = 1 if position == pos else 0

# Periods
for p in ['1', '2', '3', '4']:
    features[f'period_{p}'] = 1 if period == p else 0

# Make prediction
if st.button("Predict xG"):
    input_df = pd.DataFrame([features])
    # Ensure all expected columns exist (fill any missing with 0)
    expected_features = model.get_booster().feature_names
    for col in expected_features:
        if col not in input_df.columns:
            input_df[col] = 0
    input_df = input_df[expected_features]

    # Predict
    xg_pred = model.predict_proba(input_df)[:, 1][0]
    st.success(f"Estimated xG: **{xg_pred:.3f}**")

Writing xg_app.py

In [ ]:
#cd C:\Users\FILIP\Desktop\projekti\xG model
#streamlit run xg_app.py